% function [vocab,vectors] = read_vocab_vectors(vocab_file, vector_file, vector_size)
%  read vocabuarly and corresponding vectors generated by glove_sq.
%  The vocabulary file should store words and their counts. 
%  The bin file should store the vectors in GloVe format, and in double
%  precision.
%
% INPUT
%  vocab_file: the name of the vocabulary file
%  vector_file: the name of the vector file.
% OPTIONAL INPUT
%  vector_size: the dimension of the vectors

% OUTPUT
%  vocab: a cell array containing the words
%  vectors: the vectors. Each column is a vector.

function [vocab, vectors] = read_vocab_vectors(vocab_file, vector_file, vector_size)
    
if nargin < 3
    vector_size = 300;
end

% read vocab
[vocab, ~]=read_vocab(vocab_file);
vocab_size = length(vocab);
% read vector
fid = fopen(vector_file,'r');
vectors = fread(fid, [vector_size+1 2*vocab_size], 'double'); % columns: word vectors
vectors = vectors(1:vector_size,1:vocab_size); % ignore context vectors and bias terms
fclose(fid); 
end